server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: orderservice
#  cloud:
#    nacos:
#      server-addr: nacos:8848 # nacos服务地址
#      discovery:
#        #cluster-name: HZ #集群名称，代指上海
#        #namespace: 07819ecf-016c-4c51-9efe-da23583b90f9 #dev开发环境 id
#        ephemeral: true # 是否为临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
    com.alibaba.nacos.client.config.impl: WARN
    com.alibaba.nacos.client.naming: WARN
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10089/eureka/
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则 局部设置
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients:
      - userservice # 指定对userservice这个服务饥饿加载
#feign:
#  client:
#    config:
#      default:
#        LoggerLevel: FULL
feign:
  client:
    config:
      default: # default全局的配置
        LoggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径下的最大连接数